version: '3'
services:

  ml-toolset-gpu:
    image: dipspb/ml-toolset:latest-gpu
    build:
      context: ./docker
      dockerfile: Dockerfile.gpu
    restart: unless-stopped
    volumes:
      - ./notebooks:/src
    environment:
      PASSWORD: '12345'
    ports: [ '7777:8888' ]
    command: "bash -c 'jupyter notebook --config=/root/.jupyter/jupyter_notebook_config.py --allow-root'"

  ml-toolset-cpu:
    image: dipspb/ml-toolset:latest
    build:
      context: ./docker
      dockerfile: Dockerfile.cpu
    restart: unless-stopped
    volumes:
      - ./notebooks:/src
    environment:
      PASSWORD: '12345'
    ports: [ '7777:8888' ]
    command: "bash -c 'jupyter notebook --config=/root/.jupyter/jupyter_notebook_config.py --allow-root'"
